name: Build

on:
  push:
    branches:
      - main

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Verify Java
        run: java -version

      - name: Verify Maven
        run: mvn -version

      - name: Maven Build Project
        run: mvn clean package

      - name: Upload WAR Artifact
        uses: actions/upload-artifact@v4
        with:
          name: employee-management-webapp
          path: target/*.war

  download-artifact:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Download WAR Artifact
        uses: actions/download-artifact@v4
        with:
          name: employee-management-webapp

      - name: Verify Downloaded Artifact
        run: |
          pwd
          ls -R

  docker-build:
    needs: download-artifact
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Download WAR Artifact
        uses: actions/download-artifact@v4
        with:
          name: employee-management-webapp
          path: target

      - name: Verify Downloaded Files
        run: |
          pwd
          ls -R

      - name: Build Docker Image
        run: docker build -t employee-management-webapp:latest .

        
