name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Verify Java
        run: java -version

      - name: Verify Maven
        run: mvn -version

      - name: Maven Build Project
        run: mvn clean package

      - name: Upload War Artifact
        uses: actions/upload-artifact@v4
        with:
          name: emplyent-management-webapp
          path: target/*.war
      
